package colinlcrawford.adventofcode

object Main extends App {
  // colinlcrawford.adventofcode.day1.Day1.run()
  // colinlcrawford.adventofcode.day2.Day2.run()
  // colinlcrawford.adventofcode.day3.Day3.run()
  // colinlcrawford.adventofcode.day4.Day4.run()
  // colinlcrawford.adventofcode.day5.Day5.run()
  // colinlcrawford.adventofcode.day6.Day6.run()
  // colinlcrawford.adventofcode.day7.Day7.run()
  // colinlcrawford.adventofcode.day8.Day8.run()
  // colinlcrawford.adventofcode.day9.Day9.run()
  // colinlcrawford.adventofcode.day10.Day10.run()
  // colinlcrawford.adventofcode.day11.Day11.run()
  // colinlcrawford.adventofcode.day12.Day12.run()
  // colinlcrawford.adventofcode.day13.Day13.run()
  // colinlcrawford.adventofcode.day14.Day14.run()
  // colinlcrawford.adventofcode.day15.Day15.run()
  // colinlcrawford.adventofcode.day16.Day16.run()
  // colinlcrawford.adventofcode.day17.Day17.run()
  // colinlcrawford.adventofcode.day18.Day18.run()
  // colinlcrawford.adventofcode.day19.Day19.run()
  // colinlcrawford.adventofcode.day20.Day20.run()
  // colinlcrawford.adventofcode.day21.Day21.run()
  // colinlcrawford.adventofcode.day22.Day22.run()
  // colinlcrawford.adventofcode.day23.Day23.run()
  // colinlcrawford.adventofcode.day24.Day24.run()
  colinlcrawford.adventofcode.day25.Day25.run()
}
